Makefile, go.mod, go.sum, main.go
To start an agent, run:
```
agent serve
```
To run a job from a file, run:
```
agent run <path-to-file>
```
=> Serve a Basic HTTP API

main.go
Changes path to `/jobs` to make integration easier. It prevents running two jobs at the same time by checking the current state before running. The check if not correctly implemented yet, it needs to be locked to work flawlessly.
=> Update path and prevent double runs

examples/hello_world.yaml, job.go, main.go, shell.go
Save logs to a local file, stream them via API.
Things that need to be improved in the future:
- better local path for the file, current is /tmp/job_log.json
- cleanup of the file
- a unified interface for accessing logs in the code
=> Provide job logs via /jobs/<id>/log

job.go, main.go, shell.go
- Log started_at and finished_at for timestamps
- Log command exit code
- Preserve newlines for commands
=> Job Log improvements

pkg/jobs/job.go, pkg/jobs/lock.go, pkg/jobs/panics.go, test/e2e/docker/job_stopping.rb, test/e2e/shell/job_stopping.rb
Takes care of the following issues:
- The job was stopped but its process is not stopped cleanly. In this case, we are giving back control to agent orchestrator (with the callbacks) that can do a hard-kill on the VM level.
- The job was stopped before the terminal was available for the Job. This can happen if the stop signal arrives when the Docker is booting up.
The algorithm introduces a new re-entrant lock for making sure that only one Teardown phase is active at any given time.
fixes https://github.com/renderedtext/issues/issues/2162
=> Enter teardown phase immiditely after job stop

.semaphore/semaphore.yml, pkg/executors/docker_compose_executor.go, test/e2e/docker/container_env_vars.rb, test/e2e/docker/docker_in_docker.rb, test/e2e/docker/docker_private_image_ecr.rb, test/e2e/docker/docker_private_image_gcr.rb, test/e2e/docker/docker_registry_private_image.rb, test/e2e/docker/dockerhub_private_image.rb, test/e2e/docker/env_vars.rb, test/e2e/docker/epilogue_on_fail.rb, test/e2e/docker/epilogue_on_pass.rb, test/e2e/docker/failed_job.rb, test/e2e/docker/file_injection.rb, test/e2e/docker/file_injection_broken_file_mode.rb, test/e2e/docker/hello_world.rb, test/e2e/docker/job_stopping.rb, test/e2e/docker/no_bash.rb, test/e2e/docker/stty_restoration.rb
Some docker images do not have Bash installed. This creates an awkward situation when our logs display that environment variable export failed, but in reality, the Bash session refused to start and accept them.
Now, before starting to export the environment variables, we are checking the state of the Docker container and reporting back to the user in case there is an error reported by the Docker daemon.
=> Check and report if Bash is not available in Docker images

.semaphore/semaphore.yml, pkg/shell/process.go, test/e2e.rb, test/e2e/docker/broken_unicode.rb, test/e2e/docker/unicode.rb, test/e2e/docker/unknown_command.rb, test/e2e/shell/broken_unicode.rb, test/e2e/shell/unicode.rb, test/e2e/shell/unknown_command.rb
Now, that we are no longer waiting for the newline character to flush the output buffer, a new bug got introduced. We are cutting Unicode characters in-half.
Reminder. A UTF-8 character can span to up to 4 bytes. The highest bit in the (8th bit) marks if the character is finished or there is more upcoming information in the next byte.
Example:
A UTF-8 character spanning 3 bytes:
10101010 -> 10101010 -> 00101010
A UTF-8 character spanning 1 byte:
00101010
=> Preventing cutting unicode characters in half

pkg/shell/output_buffer.go, pkg/shell/output_buffer_test.go
Previously, we were using the `lastFlush` timestamp to determine if a broken utf-8 character is stale in the bufffer. This, however, caused a bug that prematurely flushed the broken characters, even if they weren't in the buffer long enough.
This could be reproduced with enough tries by doing `sleep 0.2 && echo "特"`.
---
In the new implemetation, we have switched to using `lastAppend` to determine if the last bytes in the buffer are ready to be flushed.
=> Fix timming issues in log buffers and UTF8 cutting

.semaphore/semaphore.yml, pkg/api/job_request.go, pkg/executors/docker_compose_executor.go, pkg/executors/docker_compose_executor_test.go, pkg/executors/executor.go, pkg/executors/shell_executor.go, pkg/executors/shell_executor_test.go, pkg/jobs/job.go, test/e2e/docker/command_aliases.rb, test/e2e/shell/command_aliases.rb
Command aliases come handy for commands that are executed during the environment setup phase.
For example, instead of 
```
git clone https://github.com/semaphoreci/toolbox.git ~/.toolbox && bash ~/.toolbox/install-toolbox && source ~/.toolbox/toolbox && echo 'source ~/.toolbox/toolbox' >> ~/.bash_profile
```
the job logs would display 
```
Setting up the Semaphore Toolbox
```
=> Introduce command aliases

.semaphore/semaphore.yml, pkg/executors/docker_compose_file.go, pkg/executors/docker_compose_file_test.go, test/e2e/docker/check_dev_kvm.rb
The reason for introducing this: android emulator won't start in compose style, because it needs `/dev/kvm` to be available in the container. See [issue](https://github.com/renderedtext/issues/issues/3231#issuecomment-593878135)
=> Add device /dev/kvm

.semaphore/semaphore.yml, Makefile, pkg/shell/process.go, pkg/shell/shell.go, pkg/shell/shell_test.go, test/e2e/shell/killing_root_bash.rb, test/e2e/shell/set_e.rb, test/e2e/shell/set_pipefail.rb
The Agent gets stuck if we abruptly close the main Bash session.
This occurs when:
- A user command explicitly exits the shell with `exit 1`
- A user command sets the error mode in the shell with `set -e` and then runs a broken command
- A user command sets the pipefail mode in the shell with `set -o pipefail` and then runs a broken piped command
This PR solves this problem by monitoring the main bash session and reporting the problem.
---
I had a hard time reproducing this bug. Running only `exit 1` was always handled properly. It took me a while to figure out how exactly to reproduce this. The trick was to have a background process that puts the Bash process in a defunct mode.
``` bash
sleep infinity &   # <- this (or any other background job) remains after exit and hangs 
exit 1
``` …
=> Handle 'exit 1', 'set -e', 'set -eo pipefail', and killing of the root shell

.semaphore/semaphore.yml, pkg/jobs/job.go, test/e2e/docker/job_stopping_on_epilogue.rb, test/e2e/shell/job_stopping_on_epilogue.rb
When stopping a job, `job.Teardown()` is called from two places:
1. `job.Run()` (after the command that was interrupted fails)
2. `job.Stop()`
If `#1` executes first, job finishes with result failed (it should be stopped). https://semaphore.semaphoreci.com/jobs/2463f0a2-e81b-42db-be66-deb66e69feab is an example of that:
```
Comparing log lines Actual=27 Expected=13
actual:   {"event":"job_finished","timestamp":1627676155,"result":"failed"}
expected: {"event":"job_finished", "timestamp":"*", "result":"stopped"}
(fail) Values for 'result' are not equal.
Makefile:30: recipe for target 'e2e' failed
make: *** [e2e] Error 1
```
If `#2` executes first and the logs are flushed before the interrupted command fails, we miss the `cmd_finished` log event. …
=> Improve stopping job

main.go, pkg/config/config.go, pkg/executors/docker_compose_executor.go, pkg/executors/docker_compose_executor_test.go, pkg/executors/executor.go, pkg/executors/shell_executor.go, pkg/executors/shell_executor_test.go, pkg/jobs/job.go, pkg/listener/job_processor.go, pkg/listener/listener.go
The `--env-vars` option accepts a comma-separated list of `NAME=VALUE` environment variables. For example:
```sh
/opt/semaphore/agent start \
--env-vars MY_HOST_VAR_1=AAAA,MY_HOST_VAR_2=BBBB \
--endpoint ... \
--token ...
```
- Job using docker compose executor example: https://semaphore.semaphoreci.com/jobs/7fb8b6f9-eee3-4b77-b1e0-fb69297cf915
- Job using shell executor example: https://semaphore.semaphoreci.com/jobs/57ed04a1-8917-4288-818d-66eaf0b17bb4
If the option doesn't receive the proper format, the agent won't start up. For example:
```
/opt/semaphore/agent start \
--env-vars MY_HOST_VAR_1=AAAA,MY_HOST_VAR_2 \
--endpoint ... \
--token ...
```
gives the following error:
```
Aug  5 17:24:14.289 : Error parsing environment variables: MY_HOST_VAR_2 is not a valid environment variable …
```
=> Add `--env-vars` option to expose environment variables to jobs from the agent

main.go, pkg/config/config.go, pkg/executors/docker_compose_executor.go, pkg/executors/docker_compose_executor_test.go, pkg/executors/docker_compose_file.go, pkg/executors/docker_compose_file_test.go, pkg/executors/executor.go, pkg/jobs/job.go, pkg/listener/job_processor.go, pkg/listener/listener.go, pkg/server/server.go
The `--files` option takes a comma separated list of file injections in the form `/host/file:/container/file`. For example:
```
/opt/semaphore/agent start \
--files /opt/semaphore/test.txt:/tmp/test.txt \
--endpoint ... \
--token ...
```
- Example job: https://semaphore.semaphoreci.com/jobs/fbafcc7b-8529-4d64-be2f-6e7710bfea33
If the option doesn't receive the proper format, the agent won't start up. For example:
```
/opt/semaphore/agent start \
--files /opt/semaphore/test.txt:/tmp/test.txt,asdasdasd \
--endpoint ... \
--token ...
```
gives the following error:
```
Aug  5 18:47:26.073 : Error parsing --files: asdasdasd is not a valid file injection
```
By default, If files passed in `--files` are not present in the host, they are ignored and not injected. If the user wants to fail the job …
=> Add `--files` option to inject files from host into main docker container

.semaphore/semaphore.yml, test/e2e/docker/docker_private_image_gcr_bad_creds.rb, test/e2e/docker/dockerhub_private_image_bad_creds.rb
For some reason, quotes are being added to the the URL now.
GCR:
```
actual   -> Error response from daemon: Get \"https://gcr.io/v2/\": unauthorized: GCR login failed. You may have invalid credentials. To login successfully, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication\n
expected -> Error response from daemon: Get https://gcr.io/v2/: unauthorized: GCR login failed. You may have invalid credentials. To login successfully, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication\n
```
Docker registry:
```
actual   -> Error response from daemon: Get \"https://registry-1.docker.io/v2/\": unauthorized: incorrect username or password\n"
expected -> Error response from daemon: Get …
```
=> Fix bad creds E2Es

.goreleaser.yml
Based on goReleaser's [docs](https://goreleaser.com/customization/homebrew/#:~:text=Git%20author%20used%20to%20commit%20to%20the%20repository).
=> Set commit_author for goreleaser

install.sh
New environment variables for installation script:
- `SEMAPHORE_AGENT_DISCONNECT_AFTER_JOB`: default is false
- `SEMAPHORE_AGENT_SHUTDOWN_HOOK`: path to the shutdown hook executed when the agent shuts down
Needed for https://github.com/renderedtext/agent-aws-stack/pull/1
=> Include additional env vars on installation script

pkg/executors/docker_compose_executor.go, pkg/executors/shell_executor.go
I've noticed this on the call.
=> Fix grammar mistake while failing to decode file content

.semaphore/semaphore.yml, main.go
The `docker_private_image_ecr` E2E test was disabled because the AWS credentials required by it are not working anymore. The test has been failing for almost a month.
Once [they are working again](https://github.com/renderedtext/tasks/issues/2662), we can enable this test again.
=> Allow SEMAPHORE_AGENT_LOG_FILE_PATH to be specified

pkg/shell/process.go
For some reason, the environment dump file isn't created in case of some errors. Here's an example from https://semaphore.semaphoreci.com/workflows/856bbbb5-afe0-4513-abac-4bb1c4fe46be?pipeline_id=212dfab6-335d-4174-8f3a-f8d01a45e222:
```
...
Mar 10 23:38:04.176 : Error creating environment from file C:\Users\ADMINI~1\AppData\Local\Temp\2\current-agent-cmd.env.after: open C:\Users\ADMINI~1\AppData\Local\Temp\2\current-agent-cmd.env.after: The system cannot find the file specified.
...
```
This fix makes sure we don't try to do anything else in case the environment file isn't there.
=> Check error reading environment file

test/hub_reference/Gemfile.lock
This has been failing our builds since a few weeks ago.
=> fix: update hub reference dependencies

pkg/eventlogger/default.go, pkg/eventlogger/httpbackend.go, pkg/eventlogger/httpbackend_test.go, pkg/jobs/job.go, pkg/listener/job_processor.go, pkg/listener/listener_test.go, pkg/listener/selfhostedapi/refresh_token.go, pkg/server/server.go, test/support/hub.go, test/support/loghub.go
The tokens generated for agents to push logs to the Semaphore API have a short duration. Currently, if a job takes longer than the duration of the token, the job will proceed as usual, but the logs will be incomplete.
In order to address this, the agent needs to refresh the token. So now, if the agent gets a 401 when trying to push logs to the Semaphore API, it will refresh the token and try again.
=> feat: refresh token used for logs

.goreleaser.yml
`windows/arm64` is not supported in Go 1.16. Previously, goreleaser emitted a warning and just didn't generate a binary. Now, it shows an error and doesn't proceed. Here, we just update the goreleaser config to not request a windows/arm64 binary, since one was not being generated anyway.
=> build: update goreleaser configuration

pkg/eventlogger/default.go, pkg/eventlogger/filebackend.go, pkg/eventlogger/httpbackend.go, pkg/eventlogger/httpbackend_test.go, pkg/jobs/job.go, pkg/listener/job_processor.go, pkg/listener/listener.go, pkg/retry/retry.go, pkg/retry/retry_test.go, pkg/server/server.go, test/support/hub.go, test/support/loghub.go
- Caps the number of log events sent in each log batch to avoid pushing too many logs at a time.
- Stop trying to send logs if the API has indicated that no more space is available to avoid sending unnecessary requests that will be just rejected by the API.
- Add some randomness to the delay we use between each batch. If the job is not finished, we use a wider range of delay between 1500ms and 3000ms. If the job is finished and we are trying to flush all the logs, we use a tighter range between 500ms and 1000ms. This is in order to avoid coordinating requests at the exact same interval.
- When flushing logs after a job is finished, we use a default timeout of 60 seconds. If, after that period, the agent still couldn't flush everything, the agent gives up and leaves the logs incomplete.
- …
=> fix: limit the amount of logs per request

pkg/eventlogger/httpbackend.go, pkg/listener/job_processor.go, pkg/random/random.go, pkg/random/random_test.go
In #156, we started using a random delay for log requests. We should follow the same idea and also use a random delay for sync requests. The current delay for those requests is fixed at 5s. Here, we update it to a random delay between 3s - 6s.
=> fix: use random delay for sync requests

main.go, pkg/eventlogger/formatter.go, pkg/listener/listener.go, pkg/listener/listener_test.go
If you have multiple agents running in AWS, with all their logs being streamed to CloudWatch, it's not easy to find an agent's logs by their name. This makes it possible:
- Adds the agent name in all the logs (for self-hosted, since hosted agents have no name, their logs will not change).
- Adds any extra fields that may be added to the logs as well.
This is what the logs for self-hosted agents will look like now:
```
Aug 11 21:07:26.242 b8-usBzORGs32cdhXlE8 : Starting to poll for jobs
Aug 11 21:07:26.243 b8-usBzORGs32cdhXlE8 : SYNC request (state: waiting-for-jobs)
Aug 11 21:07:26.243 b8-usBzORGs32cdhXlE8 : SYNC response (action: continue)
Aug 11 21:07:26.243 b8-usBzORGs32cdhXlE8 : Waiting 3.764s for next sync...
Aug 11 21:07:30.010 b8-usBzORGs32cdhXlE8 : SYNC request (state: …
```
=> fix: always include agent name in logs

pkg/executors/shell_executor_test.go, pkg/executors/ssh_jump_point.go
Agent v2.1.x introduced a regression that leads to debug sessions not working in our Mac cloud machines. The reason for that is that we started putting the ssh jump point in `$TMPDIR/ssh_jump_point`, but on Mac, `$TMPDIR` resolves to something like `/var/folders/qz/fys7r29s4cz9l_rn8zsmssz80000gn/T/`.
```
» sem debug job e9d74743-2c61-42ba-b4cf-620deb5b97ba
* Creating debug session for job 'e9d74743-2c61-42ba-b4cf-620deb5b97ba'
* Setting duration to 60 minutes
* Waiting for debug session to boot up .........
* Waiting for ssh daemon to become ready ....................
[ERROR] SSH connection can't be established; bash: /tmp/ssh_jump_point: No such file or directory; exit status 127
* Stopping debug session ..
* Session stopped
```
=> fix: always use /tmp for SSH jump point

main.go, pkg/config/config.go
Currently, we only use random names for agents. But we should allow people to set the name they want for the agent they are registering. In order to support that, we add a new `--name` configuration parameter. If not set, we generate a random name. If set, we require the name to be between 8 and 64 characters.
=> feat: allow name to be specified

go.mod, go.sum, pkg/executors/docker_compose_executor.go, pkg/executors/shell_executor.go, pkg/shell/output_buffer.go, pkg/shell/output_buffer_test.go, pkg/shell/process.go, pkg/shell/shell.go, pkg/shell/shell_test.go
The current way the process' output buffer works is:
1. It reads some output from the TTY (blocking operation)
2. Appends the TTY output to the output buffer and attempts to flush. If the buffer is not in a good state for flushing (not enough data or not old-enough data), it returns to step 1 without flushing anything.
The issue with this implementation is that if the buffer was not flushed and has some output in it, and the next TTY read operation does not produce any output for a while, the output in the buffer will remain there until the TTY read in progress finishes. That can produce output that is misleading to the customers. See: https://github.com/semaphoreci/confluent/issues/75.
The way we fix this is by using a separate goroutine for the output buffer flushes, making sure that …
=> fix: do not block output flushing on long empty TTY read

pkg/eventlogger/httpbackend_test.go, pkg/eventlogger/inmemorybackend.go, pkg/eventlogger/test_helpers.go, pkg/executors/shell_executor_test.go, pkg/jobs/job_test.go, pkg/listener/listener_test.go, pkg/shell/output_buffer.go, pkg/shell/output_buffer_test.go, test/e2e/docker/unicode.rb
1s of timeout (at 10ms and 100 chunk size) can only flush 10k of data, which is not enough if the command generates a lot of output right at the end of it. If we increase the timeout to 10s and the chunk size to 1000 when the buffer is closed, we can flush 1M of data, which should be more than enough.
Having a variable chunk size made a few tests start failing, so I had to adjust how we were asserting the outputs of commands in there.
=> fix: increase output buffer flush timeout

pkg/listener/job_processor.go, test/hub_reference/Gemfile.lock
Fixes a race condition that happens when a job finishes and is stopped around the same time:
```
API                                       Agent
| <------------- running-job ------------- |
|     job finishes (state=finished-job)    | <- job finished before the sync response was received, finished-job would be reported in the next sync request
| --------------- stop-job --------------> | <- but the agent state is overwritten to stopping-job before that happens, and the agent gets stuck
```
=> fix: race condition on stop-job

pkg/shell/process.go, pkg/shell/process_test.go
We are using a fixed-sized buffer for TTY reads of 100 bytes. Using a randomized-sized buffer seems to improve the execution of commands that generate a lot of output.
```
goos: darwin
goarch: amd64
pkg: github.com/semaphoreci/agent/pkg/shell
cpu: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
│   100b.txt    │               64-256.txt               │
│    sec/op     │    sec/op     vs base                  │
__CommandOutput_128Bytes-8   122.6m ±   1%   122.7m ±  1%        ~ (p=0.579 n=10)
__CommandOutput_1K-8         133.2m ±   1%   134.2m ±  1%        ~ (p=0.089 n=10)
__CommandOutput_10K-8        135.1m ±   1%   136.6m ±  1%   +1.09% (p=0.023 n=10)
__CommandOutput_100K-8        1.129 ± 216%    1.331 ± 92%        ~ (p=0.105 n=10)
__CommandOutput_1M-8          68.38 ±  33%    24.66 ± 28% …
```
=> fix: randomize size of TTY read buffer

pkg/executors/kubernetes_executor.go, pkg/kubernetes/client.go
Currently, if a container image can't be pulled, we keep waiting until the pod start timeout runs out. We should stop waiting immediately when we see an image pull error.
=> fix: stop waiting if image cannot be pulled

main.go, pkg/config/config.go
Same as `--name` but allows setting the agent name using an environment variable. For example:
```
export MY_AGENT_NAME=agent-pool-123
./agent start --endpoint ... --token ... --name-from-env MY_AGENT_NAME
```
This is helpful when running the agents in a Kubernetes deployment, as you can use the [Kubernetes downwards API](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/) to make the pod name available through an environment variable and use `--name-from-env MY_POD_NAME` to set the pod name as the agent name.
=> feat: add --name-from-env configuration parameter

main.go, pkg/config/config.go, pkg/jobs/job.go, pkg/kubernetes/client.go, pkg/kubernetes/client_test.go, pkg/kubernetes/image_validator.go, pkg/kubernetes/image_validator_test.go, pkg/listener/job_processor.go, pkg/listener/listener.go
Currently, there's no way to restrict the images a job can use. Here, we introduce a `--kubernetes-allowed-images` parameter. It takes a list of regexes. If all the images specified in the job match one of the regexes, the job will run. Otherwise, it will fail.
=> feat: add --kubernetes-allowed-images

main.go, pkg/config/config.go, pkg/jobs/job.go, pkg/listener/job_processor.go, pkg/listener/listener.go
We execute the pre-job hook using `bash <hook-path>`. That executes the script in a new shell, and environment changes performed during the hook execution are not carried to the shell used for the job commands. However, in some cases, it is helpful to persist in the environment changed by the pre-job hook. For example, if you want to install the Semaphore toolbox on every job in the pre-job hook.
This pull request adds a new parameter: `--source-pre-job-hook`, which instructs the agent to use `source <hook-path>` instead. By default, that parameter is false, so we keep the current behavior.
=> feat: add --source-pre-job-hook parameter

main.go, pkg/jobs/job.go, pkg/jobs/job_test.go, pkg/listener/job_processor.go, pkg/server/server.go
Currently, for cloud jobs, the Semaphore server inserts a few commands at the beginning of jobs:
- Install toolbox
- Start ssh-agent
- Connect to cache
We should move these commands from the Semaphore server to the agent. For self-hosted agents (`agent start`), we have [pre-job hooks](https://docs.semaphoreci.com/ci-cd-environment/configure-self-hosted-agent/#pre-job-hook-path), which allows the configuration of commands to execute before a job starts at the agent level. Now that we intend to support Windows agents in the cloud, we need that same behavior for cloud agents (`agent serve`).
=> feat: support --pre-job-hook-path and --files on agent serve

pkg/listener/job_processor.go, pkg/listener/selfhostedapi/sync.go, test/support/hub.go
Use the new `next_sync_after` field of the API sync response. That field is an integer specifying the number of milliseconds to wait before the next sync request. Additionally, the agent should not wait for that interval to pass if (1) the job is finished or (2) the agent was interrupted. In those cases, we trigger a new sync request even if the interval requested by the API has not passed yet.
=> feat: follow API instructions on when to sync next

.goreleaser.yml, .semaphore/release.yml
Goreleaser v1.19.x does not support `replacements`. Also, `--rm-dist` is deprecated in favor of `--clean`.
=> fix: goreleaser configuration

Dockerfile.test
[This issue](https://github.com/yaml/pyyaml/issues/724) broke our CI tests. This brings it to a working state until they fix it.
=> fix(ci): pin pyyaml to 5.3.1

pkg/executors/kubernetes_executor.go
If something goes wrong when closing the shell, we should still clean up the resources we created for the job.
=> fix: cleanup resources even if shell fails to close

.semaphore/semaphore.yml, pkg/server/server.go, pkg/server/server_test.go
The `POST /jobs` endpoint has a race condition where multiple jobs could run if the requests come simultaneously. That happens because the `s.ActiveJob` variable might not have been updated when a new request comes in. To fix that, we use a lock in that endpoint to ensure only one request is served at a time.
I also got rid of the `State` variable since we only have two states, and it's simpler only to keep track of `ActiveJob`.
I added two new tests for the `POST /jobs` endpoint:
- The first one covers the case of simultaneous requests for different job IDs
- The second covers the case of simultaneous requests for the same job ID
=> fix: POST /jobs race condition

pkg/server/server.go, pkg/server/server_test.go, test/e2e/hosted/job_logs_as_artifact_always.rb, test/e2e/hosted/job_logs_as_artifact_default.rb, test/e2e/hosted/job_logs_as_artifact_never.rb, test/e2e/hosted/job_logs_as_artifact_not_trimmed.rb, test/e2e/hosted/job_logs_as_artifact_trimmed.rb, test/e2e_support/api_mode.rb
The `GET /jobs/:id/log` endpoint should restrict access to the logs only if the job ID in the path and the job ID being run match. I also removed the `GET /job_logs` since I don't see any evidence that this endpoint is being used, and it doesn't contain the job ID, so we couldn't do this validation.
=> fix: restrict logs HTTP endpoint

pkg/jobs/job.go
We log the complete job request when using DEBUG logs for the agent. We shouldn't do that since the job request contains sensitive information. We should log only the job ID, and now that the [job ID is properly coming in the job request](https://github.com/semaphoreci/agent/pull/204), we already log it when the job starts.
=> fix: never log the complete job request

Makefile, pkg/eventlogger/httpbackend.go, pkg/listener/listener_test.go, pkg/shell/process.go, pkg/shell/process_test.go
A command termination is limited by the buffer size we use to read the command output from the TTY. Currently, we use a randomly sized buffer between 64 and 256 bytes, which is too small for high throughput command outputs. This slows the command execution itself. Through experimentation, using a randomly sized buffer in the 1k-4k range proved much faster and still used a similar amount of memory.
I've used buffer sizes of 1-2k, 1-4k, 1-8k, 2-4k, and 2-8k. Here are the results:
```
│ results__master.txt │       results__branch-1-2k.txt        │
│       sec/op        │    sec/op      vs base                │
__CommandOutput_128Bytes-2          117.1m ±  0%   116.8m ±   0%   -0.28% (p=0.023 n=10)
__CommandOutput_1K-2                128.0m ±  0%   127.4m ±   1%   -0.49% (p=0.000 n=10) …
```
=> fix: improve high log throughput job speed

pkg/executors/docker_compose_executor.go, pkg/shell/shell.go
This pull request fixes two issues:
- Proper cleanup of docker resources to ensure reentrant agents work
- Shell startup for docker-compose executor should fail if a container named `main` already exists.
The `--rm` argument of `docker-compose run` does not always work. We should take a more explicit approach and run a `docker-compose down` when the job is finished to ensure everything is deleted.
Even though the `docker-compose run` command fails due to an existing container named `main`, the "Starting the docker image..." command does not fail:
```
Oct 11 13:54:48.969 O6XvpqiMx3P2IIG98uZn : (tty) Error response from daemon: Conflict. The container name "/main" is already in use by container "4e19b104d641342b07cbd64684181600c411bbe6b72b3b8d620834730dfb557d". You have to remove (or …
```
=> fix: remove docker resources explicitly

Dockerfile.self_hosted, Makefile
To build the `Dockerfile.self_hosted` image, we are using the binary from GH from the latest tag. The problem is on a tag build, this will fail since the latest tag will not have a release yet. We should build the binary and use it, instead of relying on the GH one.
=> fix(build): do not use GH binary on docker.build

pkg/api/job_request.go, pkg/jobs/job.go
When using callbacks to inform the control plane about a job finishing, we should use the authentication token that comes with the job request.
=> fix: use auth for callbacks

.semaphore/semaphore.yml, Dockerfile.test, pkg/docker/docker.go, pkg/docker/docker_test.go, pkg/executors/docker_compose_executor.go, test/e2e/docker/compose_v1.rb
[This issue](https://github.com/docker/docker-py/issues/3194) is making our CI fail at the moment. That made me realize the docker compose executor is not smart enough to docker compose v2, it it's available. Since docker compose v1 is deprecated and [no longer receives security updates](https://docs.docker.com/compose/migrate/), we should only use it if the docker compose v2 plugin is not available.
On the docker compose prepare stage, we determine the docker compose version available, giving precedence to the v2 plugin, falling back to v1.
All the E2E tests were updated to [use docker compose v2](https://semaphore.semaphoreci.com/jobs/842b0459-871d-491c-bae0-49e978386bd8#L6369), and a new E2E that [uses docker compose v1](https://semaphore.semaphoreci.com/jobs/5b9b8510-9ff3-4919-9e15-053 …
=> fix: use docker compose v2 when available

Dockerfile.test, main.go, pkg/eventlogger/httpbackend.go
We are not currently using any HTTP timeout for our HTTP requests. We shouldn't do that. Here, we introduce a 30s timeout for all HTTP requests.
=> fix: use 30s timeout on HTTP requests

main.go, pkg/config/config.go, pkg/listener/listener.go, pkg/listener/selfhostedapi/register.go
Currently, when an agent registers to run a single job, the Semaphore control plane assigns it a random job in the queue. However, some use cases require that the agent being registered runs a single specific job, not a random one, which is not possible right now.
The registration request is changed to include a new `job_id` field. That field is used by the agent to indicate to the Semaphore control plane the specific job ID it wants to execute.
=> feat: register agent for specific job

main.go
Currently, there's no way to specify the agent configuration using environment variables. One use case where being able to do so would be helpful is when starting agents in a Kubernetes pod without a configuration file. Currently, you need to specify the `--token <VERY_SENSITIVE_TOKEN>` in the container's startup command, but that is not safe since it exposes the registration token.
We allow configuration parameters to be specified by using a `SEMAPHORE_AGENT` prefix. For example, currently you have to specify parameters as:
```
./agent start \
--endpoint test.semaphoreci.com \
--token token123 \
--disconnect-after-job
```
With this change, you will be able to do it with:
```
export SEMAPHORE_AGENT_ENDPOINT=test.semaphoreci.com
export SEMAPHORE_AGENT_TOKEN=token123
export …
```
=> feat: accept configuration from environment variables

main.go, pkg/config/config.go, pkg/jobs/job.go, pkg/kubernetes/client.go, pkg/kubernetes/client_test.go, pkg/listener/job_processor.go, pkg/listener/listener.go
New `--kubernetes-labels` configuration parameter to specify labels that are added to all the Kubernetes resources created by Kubernetes executor.
That parameter accepts a comma-separated list of key-value strings, similar to `--env-vars`. For example, if I want to list all pods created for a particular agent type, I can put the agent type name on a label:
```
./agent start \
--endpoint semaphore.semaphoreci.com \
--token "VERY_IMPORTANT_TOKEN" \
--kubernetes-executor \
--kubernetes-labels app=semaphore,semaphoreci.com/agent-type=s1-testing
```
And then use it when listing pods:
```
kubectl get pods -l semaphoreci.com/agent-type=s1-testing
```
=> feat: add labels to kubernetes resources

pkg/retry/retry.go, pkg/shell/output_buffer.go, pkg/shell/output_buffer_test.go, pkg/shell/process.go, pkg/shell/shell_test.go
Related to https://github.com/renderedtext/tasks/issues/5043.
Currently, if a command generates more than 1MB of output right when it ends, the agent is not able to consume all that output in time.
We are currently sleeping 10ms between each output buffer flushing operation. We shouldn't do that since it limits how much output we can consume. We should just let the output buffer flush itself as fast as it can, for as long as we want it.
We achieve that by controlling how much time is spent on flushing with a context that expires after 1 minute instead of using a maximum number of attempts and a sleeping period between each attempt.
=> fix: no sleep when flushing output buffer

docs/kubernetes-executor.md, pkg/kubernetes/client.go, pkg/kubernetes/client_test.go
Currently, when using the Kubernetes executor, if additional containers (db, redis, ...) are used in a job, they are only available through localhost, and not through their DNS names, like with the docker compose executor.
We populate the [hostAliases](https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/) field for the pod created for the job with the container names coming from the Semaphore YAML.
=> fix: configure hostAliases for sidecar containers

pkg/executors/kubernetes_executor.go
https://github.com/renderedtext/tasks/issues/5830
When injecting files, the Kubernetes executor is not properly resolving their paths. It is currently using the home directory where the agent is running, not where the job is running. This makes it hard for troubleshooting issues with file injection.
Use a similar resolving logic as the one used in the docker-compose executor: inject file into the home directory where the job is running unless the file path is already an absolute one or already contains `~`. Additionally, we also include a few additional commands right after the PTY session is started to gather a little bit more detail into the user running the commands, which should help us troubleshoot permission issues on the containers being used to run the jobs.
=> fix(kubernetes): do not use home directory from agent when injecting files

pkg/executors/kubernetes_executor.go
Related to https://github.com/renderedtext/tasks/issues/5830
We are not logging the actual error messages from the commands being executed when injecting files in the Kubernetes executor, which makes it hard to troubleshoot issues.
Use `GetOutputFromCommand()` to execute the command and get its output to log it in case of errors.
=> fix(kubernetes): log error messages from commands when injecting files

.goreleaser.yml
https://github.com/renderedtext/tasks/issues/6241
GoReleaser v2 was released a [few weeks ago](https://goreleaser.com/blog/goreleaser-v2/), which caused [this job](https://semaphore.semaphoreci.com/jobs/878c8dd6-84de-4212-8520-ee92059474fa) to fail. This pull request updates the GoReleaser configuration appropriately to use the v2.
=> fix: goreleaser config for goreleaser v2

.semaphore/semaphore.yml, main.go, pkg/server/server.go, test/e2e/docker/docker_private_image_ecr.rb, test/e2e/docker/docker_private_image_ecr_account_id.rb, test/e2e/docker/docker_private_image_ecr_account_id_v2.rb, test/e2e/docker/docker_private_image_ecr_v2.rb, test/e2e/docker/docker_private_image_gcr.rb, test/e2e/docker/docker_registry_private_image.rb, test/e2e/docker/dockerhub_private_image.rb
https://github.com/renderedtext/tasks/issues/6471
Currently, the cloud agent will retry sending the job finished callback 60 times, with a 1s wait before each attempt, meaning it will retry for 1 minute. We should make that retrying window wider, so I'm increasing it to 5 minutes, and also adding a `--callback-retry-attempts` option to make it configurable.
=> fix: make callback retry attempts configurable

main.go, pkg/eventlogger/default.go, pkg/eventlogger/httpbackend.go, pkg/eventlogger/httpbackend_test.go, pkg/jobs/job.go, pkg/listener/job_processor.go, pkg/listener/listener.go, pkg/listener/listener_test.go, pkg/listener/selfhostedapi/api.go, pkg/listener/selfhostedapi/disconnect.go, pkg/listener/selfhostedapi/get_job.go, pkg/listener/selfhostedapi/refresh_token.go, pkg/listener/selfhostedapi/register.go, pkg/listener/selfhostedapi/sync.go, pkg/server/server.go, test/support/hub.go, test/support/loghub.go
https://github.com/renderedtext/tasks/issues/6557
We are not currently setting the User-Agent HTTP header on the HTTP requests made to the Semaphore control plane. This pull request changes that and includes that header in the:
- Requests to `/api/v1/self_hosted_agents` endpoints
- Requests to `/api/v1/logs` endpoint
- Job callback requests
=> feat: set User-Agent HTTP header on requests

.semaphore/release.yml, .semaphore/semaphore.yml, Makefile, go.mod, main.go, pkg/config/config.go, pkg/server/server.go
https://github.com/renderedtext/tasks/issues/6702
For agent serve and docker-compose jobs, we always add a `/dev/kvm` device in the docker compose YAML for the job. We should make that configurable, since not all environments have that device available. For that, we add a new `--expose-kvm-flag`.
- Update Go to 1.22.7 due to vulnerability
- Ignore kubectl when scanning Docker image
=> feat: new --expose-kvm-device flag

pkg/executors/shell_executor.go, pkg/kubernetes/client_test.go, pkg/shell/env.go, pkg/shell/env_test.go
https://github.com/renderedtext/tasks/issues/6922
Since we don't need the temporary file containing the environment variables in Windows (no PTY), we are not creating that file. That is an issue for Windows debug jobs which cannot access those values in any way.
Create the file for Windows jobs too. The file will be created in the `$env:Temp` directory, usually `C:\Users\<username>\AppData\Local\Temp`. The file is created with a `.ps1` extension and uses the PowerShell format for defining environment variables, so the user can "source" it as well.
Note: `source` is not available in PowerShell, but you can do something like `. <script-name>.ps1`
=> fix: expose temp file with environment variables in Windows

.semaphore/semaphore.yml, pkg/compression/gzip.go, pkg/compression/gzip_test.go, pkg/jobs/job.go, test/e2e.rb, test/e2e/hosted/job_logs_as_artifact_compressed.rb, test/e2e_support/api_mode.rb
https://github.com/renderedtext/tasks/issues/6930
Since the artifacts API does not support multipart uploads yet, uploading the job logs as an artifact is not possible if the amount of job logs produced is bigger than the amount of data the artifact storage backend can take. For example, when using S3 as the backend for artifact storage, we are limited to 5GB files.
If the file is above a certain threshold, we compress it before uploading it as an artifact. The default threshold is 100M, but it can be configured with the `SEMAPHORE_AGENT_LOGS_COMPRESSION_SIZE` environment variable.
=> feat: compress job logs above a threshold before uploading it as an artifact

go.mod, go.sum, install.sh
The artifact CLI lookup in job log upload was failing because
exec.LookPath("artifact") couldn't find the CLI when running under launchd.
Added PATH environment variable to launchd daemon configuration to include
standard system paths (/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin).
=> fix: add PATH environment variable to launchd daemon configuration
