semaphoreci/agent

- job.go
- main.go
- shell.go
To start a job:
```
curl http://0.0.0.0:8000/run -d '{"commands": [{"directive": "echo hello"}]}'
```
> API for running jobs

- examples/hello_world.yaml
- job.go
- shell.go
Exports env vars and injects files into the job. 
Support for tracking this progress is not yet supported.
> Export env vars, inject files

- job.go
Sends callbacks when job starts and finishes.
The started callback always sets SSH port to 22. This needs to be fixed in the future.
The finished callback always sets the result to "passed". This needs to be fixed in the future.
> Send callbacks on job start and finish

- examples/failure.yaml
- job.go
- shell.go
Calculates proper result for job based on job's statuses.
> Calculate job result

- .goreleaser.yml
- main.go
Gorelaser will manage versions by ldflags -X
> goreleaser to manage versions

- .semaphore/semaphore.yml
- pkg/jobs/job.go
This aids with debugging a bug with false negative job result.
> Logging command finishing

- pkg/api/job_request.go
- pkg/server/server.go
Fixes https://github.com/semaphoreci/agent/issues/45
> Handle identical calls with idempotent response

- .semaphore/semaphore.yml
- Makefile
- pkg/executors/docker_compose_executor.go
- pkg/executors/shell_executor.go
- test/e2e/docker/stty_restoration.rb
- test/e2e/shell/stty_restoration.rb
fixes https://github.com/semaphoreci/agent/issues/40
fixes https://github.com/renderedtext/issues/issues/1715
> Store stty options and restore to sanity before executing commands

- .semaphore/semaphore.yml
- pkg/executors/docker_compose_executor.go
- test/e2e/docker/container_custom_name.rb
If the first container in the build is not named main, the build will fail.
This will allow custom names for the first container.
> Custom name for 'main' container

- pkg/shell/output_buffer.go
- pkg/shell/output_buffer_test.go
- pkg/shell/process.go
- test/e2e/docker/unicode.rb
- test/e2e/shell/unicode.rb
The original issue described in https://github.com/semaphoreci/agent/pull/77.
> Fix for unicode box drawing characters

- pkg/eventlogger/httpbackend.go
Use lock to avoid race condition when pushing logs. This solves the flakiness on the `job_stopping` e2e.
Example:
```
Jul 20 19:49:42.283 : Pushing logs to http://hub:4567/api/v1/logs/E7BC7DE0-6789-48EB-8667-2A01D70D439A?start_from=0
Jul 20 19:49:43.283 : No logs to push - skipping
Jul 20 19:49:44.282 : No logs to push - skipping
Jul 20 19:49:45.279 : No logs to push - skipping
Jul 20 19:49:46.285 : Pushing logs to http://hub:4567/api/v1/logs/E7BC7DE0-6789-48EB-8667-2A01D70D439A?start_from=6
Jul 20 19:49:46.287 : Stopped streaming logs
Jul 20 19:49:46.287 : Pushing logs to http://hub:4567/api/v1/logs/E7BC7DE0-6789-48EB-8667-2A01D70D439A?start_from=6
Jul 20 19:49:46.293 : All logs successfully pushed to http://hub:4567/api/v1/logs/E7BC7DE0-6789-48EB-8667-2A01D70D439A
```
> Lock when pushing logs

- pkg/listener/job_processor.go
- `LastSuccessfulSync` was not being updated after successful sync requests
- `LastSuccesfulSync` -> `LastSuccessfulSync`
> Always update LastSuccessfulSync timestamp

- .semaphore/semaphore.yml
- Makefile
- lint.toml
- main.go
- pkg/api/job_request.go
- pkg/config/config.go
- pkg/eventlogger/default.go
- pkg/eventlogger/httpbackend.go
- pkg/executors/docker_compose_executor.go
- pkg/jobs/job.go
- pkg/listener/job_processor.go
- pkg/listener/listener.go
- pkg/listener/selfhostedapi/api.go
- pkg/listener/selfhostedapi/disconnect.go
- pkg/listener/selfhostedapi/get_job.go
- pkg/listener/selfhostedapi/logs.go
- pkg/listener/selfhostedapi/register.go
- pkg/listener/selfhostedapi/sync.go
- pkg/osinfo/osinfo.go
- pkg/server/server.go
- pkg/shell/process.go
I don't necessarily agree with everything that `revive` proposes, but a consistent shared standard outweighs any of my personal preferences.
> Add a code linter to the CI suite

- pkg/jobs/job.go
Just outdenting a if-elseif-else block.
> fix: linter warning

- test/hub_reference/Gemfile.lock
Closes:
- https://github.com/semaphoreci/agent/security/dependabot/19
- https://github.com/semaphoreci/agent/security/dependabot/18
- https://github.com/semaphoreci/agent/security/dependabot/17
> fix: update rack to 2.2.8.1

- .github/workflows/test.yml
- .semaphore/release.yml
- .semaphore/semaphore.yml
- go.mod
- go.sum
https://github.com/renderedtext/tasks/issues/6237
> fix: upgrade to Go 1.22

- .semaphore/release.yml
https://github.com/renderedtext/tasks/issues/6241
> fix: publish new image version on release promotion

- .goreleaser.yml
Closes https://github.com/semaphoreci/agent/issues/243
> build: include binary for ppc64le to release

- go.mod
Related to https://github.com/renderedtext/tasks/issues/6302
> fix: upgrade to Go 1.22.4

- test/hub_reference/Gemfile.lock
Just an update of a library in test "project" CI is complaining about.
> fix(test): security issue in tests: Rack::QueryParser bypass
